CREATE TABLE transacoes (
    id UUID PRIMARY KEY,
    valor DOUBLE PRECISION NOT NULL,
    data_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    tipo VARCHAR(20) NOT NULL,

    CHECK (tipo IN ('DEPOSITO', 'SAQUE', 'TRANSFERENCIA', 'PAGAMENTO', 'CREDITO'))
);
